### PR TITLE
improve pretty location class name

### PR DESCRIPTION
**Pull request by Uysim**
This pull request base on discussion in google group of [pretty print is not pretty](https://groups.google.com/forum/#!searchin/ruby-shrine/pretty%7Csort:date/ruby-shrine/M8KmbVQz6mk/mqz4J9BPAgAJ). 

It is improve the way we transform the class name

### CODE REVIEW

**Comment by janko** [comment]
Thank you for the pull request!

Sorry for the delay on my side, I will try to test and merge it tomorrow. In the meantime, I noticed this can be only used for people who are using Active Support. Could we change it so that it's easy to get underscores without Active Support?

Also, I don't think we need any other transformation, so I would personally just have `class_underscore: true`, and implement the underscoring in Ruby. If people need any additional transformations, they can just modify the pretty location string directly, e.g:

```rb
def generate_location(io, **options)
  location = super
  "prefix_#{location}"
end
```

**Comment by Uysim** [comment]
@janko actually I think pass in Proc is make it easier to customize but that is ok. I have change to use only `class_underscore` option.

**Comment by jrochkind** [comment]
The title says "pretty print", to be clear we're talking about the `pretty_location` plugin, which controls the `id` of an attachment -- that is, the path it is stored at in storage.

I think we need to make it as easy as possible for a particular Uploader to customize it's id/path creation in whatever ways it wants. I don't totally understand the current shrine 'best practice' for customizing id/path in arbitrary ways. 

I'm not sure that "underscore version of the class name" is important enough to make an option all by itself. But it might be, if this is really something lots of people want? I'm not sure. 

I think the more important thing is making it clear what the recommended pattern is for _arbitrary_ changes. And having one that doesn't require you to "reinvent the wheel", re-doing things that are common/shared/already implemented. So I'm intrigued by the "proc" suggestion; although if it's just a proc for "how do we turn a class into a string", that's only one part of the space.

**Comment by janko** [comment]
@jrochkind This sounds like a separate discussion that doesn't belong with this PR.

The underscore behaviour should really have been the default already, and since making it the default behaviour *now* isn't an option due to backwards compatibility, I think it's fine to at least provide users an option.

@Uysim Thanks, this looks good. Would you mind also updating the documentation?

**Comment by Uysim** [comment]
@jrochkind worry wrong typing

@janko I have update the document

**Pull request merged**
