### PR TITLE
#delete_prefixed

### LINKED ISSUE #409: Add clear_prefixed/delete_prefixed method for each Storage adapter
Similar to ActiveStorage delete_prefixed. 

I wound up needing it for some custom use of low-level Shrine::UploadedFile api, when I was constructing some related files under the same prefix myself. 

Every Storage adapter would have to provide it's own implementation. 

https://api.rubyonrails.org/classes/ActiveStorage/Service.html#method-i-delete_prefixed

https://github.com/rails/rails/search?q=delete_prefixed&unscoped_q=delete_prefixed

### PR DESCRIPTION
**Pull request by jrochkind**
Closes #409

This adds #delete_prefixed to Shrine:Storage::S3 and Shrine::Storage::FileSystem

Also adds docs to creating_storages.md to explain and recommend #delete_prefixed

* Does not add to Memory, although it could add an inefficient imp without too much trouble. 

## Warning: No test for S3

I could not manage to get a stub_request-style setup to work to test S3, although it oughta be possible. I spent some time with the S3 stub_request docs and experimenting, just couldn't manage to get anywhere yet. Advice or help welcome. 

I DID test it locally -- I wrote a test on a _real_ S3 bucket with my own credentials, and made sure it passed (at first it didn't, finding a bug!). So I am confident in the code at present. But that's not reliable for preventing future regressions of course. 

## Linter

I DID add testing for delete_prefixed to the linter. Following example of existing 'optional' features tested by linter, it only tests it if respond_to?(:delete_prefixed). 

So FileSystem is actually double-tested, once by it's own tests, and once by linter. (linter was pre-existing not being run on S3).

I think it would be nice to add an option to the linter where it _insists_ on certain optional features, like `clear!` and `delete_prefixed`. As a develper using shrine, it can be nice to know whether I can rely on the full suite of utilities with a given storage, that would answer that question, and give third-party developers a target for 'maximal' implementation. But just mentioning in passing, that'd be for discussion or implementation elsewhere, not here.

### CODE REVIEW

**Comment by janko** [comment]
I changed `#delete_prefixed` to accept prefixes without trailing slash, so that it's consistent with other `:prefix` options Shrine currently has. That also simplifies storage implementations a bit.

Other than that, everything else looks ready, so I'm merging.

**Comment by jrochkind** [comment]
Oh, I thought it already did accept without the trailing slash? Oh, okay, before it accepted with _or_ without the trailing slash, now it _only_ accepts without the trailing slash -- if you supply a trailing slash yourself, I think it may not actually  actually work?

I think that's an unnecessary gotcha for users-- especially because ActiveStorage takes/requires a trailing slash on argument, so anyone coming from there is going to be used it. 

So I prefer the former way, and don't think the extra one line of trailing slash normalization is too big a price to pay. But your call!

**Comment by janko** [comment]
I see your point of view and agree, I added the support back – https://github.com/shrinerb/shrine/commit/8b05b10812678cc958cf00785e9f0fb8f3a35cb9

**Comment by jrochkind** [comment]
Cool, thanks @janko . I believe it is safer to pass a string _with_ a trailing prefix to AWS API. My original code did that too. 

But it may not actually matter, I was just trying to be lazy and not totally think through it. Like, are we sure that the AWS API won't find a key "a/aaa/b.jpg" if you call `bucket.objects(prefix: "a/a")`?  I think the S3 API may actually be a strict prefix, and not care about terminating at a `/`. I was not sure, so made sure to call `bucket.objects(prefix: "a/a/")` -- whether the user passed in `a/a` or `a/a/`. 

I think your current code may normalize both to `a/a` instead?  Are we sure it will work as desired? I _think_ the tests I wrote for the Linter should test against this; and that they are being run against minio on travis. Assuming I properly tested that, and minio behaves the same as S3., and the tests haven't been changed since I wrote them to no longer test that....

**Comment by janko** [comment]
The behaviour of my change should be the same as with the code you wrote originally, using a trailing slash for S3 storage. I agree it’s probably safer that way.

**Comment by jrochkind** [comment]
Okay, just for context, I have confirmed that S3 needs a trailing slash in the arg to `objects(prefix:` if you don't want it to match on partial path component. 

    storage_s3.upload(some_file, "dir/aaaa/file.png")

    storage_s3.bucket.objects(prefix: "dir/a").to_a
    # => includes the object with `@key="dir/aaa/a.png"`

    storage_s3.bucket.objects(prefix: "dir/a")
    # => does not 

But I see now that  8b05b10 does looks like you are normalizing to make sure you include a slash before sending to S3 `objects(prefix:`, I was misreading it before. So ok!

**Pull request merged**
