### PR TITLE
extract_metadata in StoreDimensions should have optional second arg

### PR DESCRIPTION
**Pull request by jrochkind**
The store_dimensions method being overridden has an optional second arg. https://github.com/shrinerb/shrine/blob/ee1ced8c99531cbd90df13e75c64953c1e07419a/lib/shrine.rb#L231

By overriding without a default param, the override made the method now have a required second param, basically changing it's signature with the override. Have a matching default arg to preserve semantics on override.

Note I didn't add a test yet, not sure if I should?

### CODE REVIEW

**Comment by jrochkind** [comment]
CI seems to be failing on JRuby for reasons unrelated to this PR. We should probably fix the build on JRuby though.

**Comment by janko** [comment]
Good catch, thanks for the patch! Could you add a test for that in the `store_dimensions` plugin tests? 

> CI seems to be failing on JRuby for reasons unrelated to this PR. We should probably fix the build on JRuby though.

Yeah, JRuby just won't give me a break – https://github.com/shrinerb/shrine/commit/8696a36fd4e878a97e03fa7b1de15754e6cf0344, https://github.com/shrinerb/shrine/commit/f8c87f4597587fb3a5850edd00ac438c94771ea1, https://github.com/shrinerb/shrine/commit/50069f6fa610cd472b4d1f4c1932326d4af616e7. I'll push a fix for that failure. Looking forward to increasing the matrix of failures with TruffleRuby 😄

**Comment by jrochkind** [comment]
Not totally sure what test to add. 

I can add a test that says store_dimension's `extract_metadata` has an optional second arg... but if the original `extract_metadata` changes it's signature, the test won't pass. It may have gotten this way because of a change in the original signature that got the out of sync?

Not sure a good way to make sure "overridden signature matches original". Hm the #parameters reflection method might work, and is available in 2.3. This might have been more than you were asking for, but I'll see if I can add that, haha.

**Comment by jrochkind** [comment]
that worked, why not.

**Comment by janko** [comment]
That's a pretty neat approach, I hadn't thought of that 👍😃

**Comment by jrochkind** [comment]
> * Fix `store_dimensions` plugin making second argument in `Shrine#extract_metadata` mandatory (@jrochkind)

I think that says the opposite of what was done maybe?

**Pull request merged**
