### PR TITLE
add bundle exec to sequel in demo README

### PR DESCRIPTION
**Pull request by hide-furusawa**

### CODE REVIEW

**Comment by hmistry** [comment]
Did you have an issue running the command without `bundle exec`?

**Comment by hide-furusawa** [comment]
I got error. and I thought it would be better to match it with the rackup command to README.

**Comment by janko** [comment]
> I got error

Which error?

**Comment by janko** [comment]
I'm going to merge this, as I don't see any harm in adding `bundle exec`, and I trust you that you had problems without. I was just curious what problem it was, so that I increase my understanding of Ruby. Thanks for the patch!

**Comment by hide-furusawa** [comment]
Thank you for the reply and merge.
I will use shrine .

**Pull request merged**
