### PR TITLE
Don't lookup attachment class on every attacher read

### PR DESCRIPTION
**Pull request by printercu**
Hi!

I've changed `class_eval` to `define_method` for `*_attacher` methods, so it has access to attachment (and it's attacher) inside. This removes `ancestors.grep.find` to get attacher class dynamically.

### CODE REVIEW

**Comment by hmistry** [comment]
Thank you for making a PR to improve Shrine.

I'm not seeing a huge benefit to this because the `attacher` is already cached on L419 so `ancestors.grep.find` only runs once when the module is included in the model. The only benefit is not searching through `ancestors` but that is typically a short list.

@janko-m any thoughts on this?

PS - According to Aaron in 2013, `define_method` can be faster and consumes less memory but it creates closures and as such referenced objects in it may not get GC'd.

**Comment by printercu** [comment]
This methods are mixed to active record objects. When `user.image` is called it calls `user.image_attacher` which call all the chain, and creates attacher for this user (old line: `attacher_class.new(self, :#{name}, options)`). `other_user.image` repeats everything again.

**Comment by janko-m** [comment]
@printercu Thanks a lot for the pull request. This looks like an improvement to me, but I'll take a closer look tomorrow.

Yeah, the downside of `module_eval`/`class_eval` is that you cannot pass them potentially anonymous classes, at least not to my knowledge.

**Comment by jrochkind** [comment]
> module_eval/class_eval is that you cannot pass them potentially anonymous classes, at least not to my knowledge.

In the general case, you can call module_eval/class_eval on anonymous classes/modules just fine (if I understand what 'anonymous classes' means), but I don't know if it helps here specifically. 

```ruby
something = Class.new do
end

something.class_eval do
   def foo ; "foo" ; end
end

something.new.foo #=> "foo"
```

**Comment by janko-m** [comment]
@jrochkind I meant passing other anonymous classes into the `class_eval`/`module_eval` _body_:

```rb
something = Class.new {}

module_eval <<-RUBY
  def foo
    #{something} # this probably won't work
  end
RUBY
```

**Comment by janko-m** [comment]
> PS - According to Aaron Patterson in 2013, define_method can be faster and consumes less memory but it creates closures and as such referenced objects in it may not get GC'd.

@hmistry I think that should be ok, because the only objects that couldn't be GC'd here would be few strings and symbols, and the `Shrine::Attachment` instance which can't be GC'd anyway, because it's included in the model and the model needs to keep the reference to it in the `ancestors` list.

**Pull request merged**
