### PR TITLE
Allow S3 storage upload option to disable default content-disposition param

### PR DESCRIPTION
**Pull request by jrochkind**
Also added test for ability to override default content-disposition. That was already possible, but I wasn't certain, and there wasn't a good test already.

### CODE REVIEW

**Comment by janko** [comment]
Thanks for the additional test coverage!

Considering that the default behaviour when `Content-Disposition` is unspecified is `inline` (though according to spec is `attachment` AFAIK), I'm not sure about how useful it is to support `false`, since the user can already specify `ContentDisposition.inline` or `ContentDisposition.attachment` if they want to avoid the filename.

**Comment by jrochkind** [comment]
I'm not following. By default the storage adds a content-disposition header which not only specifies `inline`, but specifies a filename in the content-disposition header. 

The filename specified is taken from the shrine metadata filename (ie, original filename), where available, and may not be the same as the last path component of the URL (ie, the `id`), which is what the what the browser will default to if no content-disposition is given. 

If there is no shrine-metadata filename, then the storage by default won't add a content-disposition header at all. 

However, even if there is a shrine metadata filename, I may not want the storage to set content-disposition header as metadata with the S3 object. But there's no way to stop it. So `false` is a way to stop it, and have no content-disposition header set at all. So when retrieving a URL from S3, the browser will just do whatever it was going to do with no content-disposition header. 

Or for whatever other reason I simply don't want to set a default content-disposition header in S3 when setting the S3 object. Perhaps I plan to always set one in an individual signed-url on every access, and don't want the default stored-with-object one there to confuse me. There is no requirement from S3 that a content_disposition parameter be set when storing a key in S3, but without this patch there's no way to stop the storage from setting one -- _if_ there is a shrine metadata filename key set. If there's not, it won't set one by default. 

Maybe this is not a use case, you're saying there's no need anyone would have to prevent a default content_disposition header being sent to S3 when the object is set? That may be. Just want to make sure we're talking about the same thing.

**Comment by janko** [comment]
> Maybe this is not a use case, you're saying there's no need anyone would have to prevent a default content_disposition header being sent to S3 when the object is set?

I do want users to be able to cancel the default `:content_disposition` that S3 storage sets when filename is present. However, according to the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition), when no `Content-Disposition` header is set, the client should assume `Content-Disposition: inline`. That's what I deduced from this paragraph:

> The first parameter in the HTTP context is either `inline` (**default value**, indicating it can be displayed inside the Web page, or as the Web page) or `attachment` (indicating it should be downloaded; most browsers presenting a 'Save as' dialog, prefilled with the value of the `filename` parameters if present).

This means that if the user wants to get the default behaviour, in other than setting no value for `:content_disposition` (which is currently not possible, as you said), they can also set `content_disposition: "inline"`. Yes, that won't achieve 100% the same thing, because `GET <S3 object URL>` will return `Content-Disposition: inline` instead of no `Content-Disposition`, but it should produce the same *behaviour* (because `inline` is assumed as default).

Furthermore, I see that when you don't specify `:content_type` for an S3 object, requesting it will return an empty `Content-Type` response header. This means it's "ok" to set empty response headers, in which case you could also set `content_disposition: ""`.

So yes, while disabling `:content_disposition` is technically not possible, you can already achieve the same behaviour with `content_disposition: "inline"` or `content_disposition: ""`. That's why I don't see the need for a 3rd option of getting the same behaviour.

**Comment by jrochkind** [comment]
Ah, I get it! Sorry for taking a second to get it. OK, reasonable! Closing this one.

**Pull request closed without merging**
